# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: saivarunjamalpoor # the website title (if blank, full name will be used instead)
first_name: Sai
middle_name: Varun
last_name: Jamalpoor
contact_note: >
  You can reach me via email at saij@iiitd.ac.in
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  PhD Student at IIIT-Delhi. Researching Multi-Modal Language Models.
footer_text: ""
keywords: video-generation, video-understanding, multimodal-learning, vision-language-models
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://thesvj.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: thesvj
blog_description: PhD Student at IIIT-Delhi researching Multimodal AI
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo:
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  dark_theme: dark
  light_theme: light
  emit_metadata: 0
  lang: en

disqus_shortname: # leave blank to disable Disqus comments

external_sources:

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  teachings:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor

keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-cache-bust
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-socials
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Jamalpoor]
  first_name: [Sai, Sai Varun, Saij, SV., sai, sai varun]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# JSON Resume
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
